"""update basemodel, fstorage,dbstorage

Revision ID: 29651e05637a
Revises: 4500b496b597
Create Date: 2024-01-07 22:18:08.806135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29651e05637a'
down_revision = '4500b496b597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
