"""Added Cascade to the reviews in place model

Revision ID: 4500b496b597
Revises: 5a3c8158cedc
Create Date: 2024-01-07 17:22:49.502343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4500b496b597'
down_revision = '5a3c8158cedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
