"""Added Cascade to the city model

Revision ID: 5a3c8158cedc
Revises: 7e82274d2be3
Create Date: 2024-01-07 11:54:14.322708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3c8158cedc'
down_revision = '7e82274d2be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
