"""Added Cascade to the state model

Revision ID: 7e82274d2be3
Revises: 
Create Date: 2024-01-07 10:53:00.882293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e82274d2be3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amenities', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('amenities', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('cities', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('cities', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('place_amenity_ibfk_1', 'place_amenity', type_='foreignkey')
    op.drop_constraint('place_amenity_ibfk_2', 'place_amenity', type_='foreignkey')
    op.create_foreign_key(None, 'place_amenity', 'places', ['place_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'place_amenity', 'amenities', ['amenity_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('places', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('places', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('reviews', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('states', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('states', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('states', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('states', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('reviews', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('places', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('places', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'place_amenity', type_='foreignkey')
    op.drop_constraint(None, 'place_amenity', type_='foreignkey')
    op.create_foreign_key('place_amenity_ibfk_2', 'place_amenity', 'amenities', ['amenity_id'], ['id'])
    op.create_foreign_key('place_amenity_ibfk_1', 'place_amenity', 'places', ['place_id'], ['id'])
    op.alter_column('cities', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('cities', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('amenities', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('amenities', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
